version: '3.3'

services:
  damap-be:
    build:
      context: ./
    container_name: "damap-backend"
    restart: "unless-stopped"

  damap-db:
    image: postgres:12
    container_name: "damap-db"
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_DB: damap
      POSTGRES_USER: ${DAMAP_POSTGRES_USER:-damap}
      POSTGRES_PASSWORD: ${DAMAP_POSTGRES_PASSWORD:-pw4damap}
    volumes:
     - damap-db-data:/var/lib/postgresql/data
    restart: "unless-stopped"

  keycloak:
    image: jboss/keycloak
    container_name: "keycloak"
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_POSTGRES_USER:-keycloak}
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-keycloak}
      DB_SCHEMA: public
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
      KEYCLOAK_IMPORT: /tmp/sample-damap-realm-export_production.json
    ports:
      - "8087:8080"
    volumes:
      - ./docker/sample-damap-realm-export_production.json:/tmp/sample-damap-realm-export_production.json
    restart: "unless-stopped"
    depends_on:
      - keycloak-db
  
  #keycloak won't work on the same db container used by damap-be, so we define a new one
  keycloak-db:
    image: postgres:12
    container_name: "keycloak-db"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-keycloak}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: "unless-stopped"

  damap-fe:
    build:
      context: ../damap-frontend
    container_name: "damap-frontend"
    restart: "unless-stopped"

  api-mock:
    image: clue/json-server
    container_name: "mock-api"
    command: db.json --routes routes.json
    volumes:
      - ./docker/api-mock/data/db.json:/data/db.json
      - ./docker/api-mock/data/routes.json:/data/routes.json
    ports:
      - "8091:80"
    restart: "unless-stopped"

  nginx:
    image: registry.hub.docker.com/library/nginx
    container_name: "nginx"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: "unless-stopped"

volumes:
  damap-db-data:
  keycloak-db-data:
